# Generated by Django 4.0.2 on 2023-09-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approver', '0004_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(null=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_modified_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'db_table': 'master.config',
            },
        ),
    ]
