# Generated by Django 4.0.2 on 2023-09-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
